INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES
('hfnu.admin.ban', 'havefnubb~acl2.admin.ban'),
('hfnu.admin.category', 'havefnubb~acl2.admin.category'),
('hfnu.admin.category.create', 'havefnubb~acl2.admin.category.create'),
('hfnu.admin.category.delete', 'havefnubb~acl2.admin.category.delete'),
('hfnu.admin.category.edit', 'havefnubb~acl2.admin.category.edit'),
('hfnu.admin.config', 'havefnubb~acl2.admin.config'),
('hfnu.admin.config.edit', 'havefnubb~acl2.admin.config.edit'),
('hfnu.admin.forum', 'havefnubb~acl2.admin.forum'),
('hfnu.admin.forum.create', 'havefnubb~acl2.admin.forum.create'),
('hfnu.admin.forum.delete', 'havefnubb~acl2.admin.forum.delete'),
('hfnu.admin.forum.edit', 'havefnubb~acl2.admin.forum.edit'),
('hfnu.admin.index', 'havefnubb~acl2.admin.index'),
('hfnu.admin.member', 'havefnubb~acl2.admin.member'),
('hfnu.admin.notify.delete', 'havefnubb~acl2.admin.notify.delete'),
('hfnu.admin.notify.list', 'havefnubb~acl2.admin.notify.list'),
('hfnu.admin.rank.create', 'havefnubb~acl2.admin.rank.create'),
('hfnu.admin.rank.delete', 'havefnubb~acl2.admin.rank.delete'),
('hfnu.admin.rank.edit', 'havefnubb~acl2.admin.rank.edit');

INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES
('hfnu.admin.ban', 'admins', ''),
('hfnu.admin.ban', 'moderators', ''),
('hfnu.admin.category', 'admins', ''),
('hfnu.admin.category', 'moderators', ''),
('hfnu.admin.category.create', 'admins', ''),
('hfnu.admin.category.delete', 'admins', ''),
('hfnu.admin.category.edit', 'admins', ''),
('hfnu.admin.config', 'admins', ''),
('hfnu.admin.config', 'moderators', ''),
('hfnu.admin.config.edit', 'admins', ''),
('hfnu.admin.forum', 'admins', ''),
('hfnu.admin.forum.create', 'admins', ''),
('hfnu.admin.forum.delete', 'admins', ''),
('hfnu.admin.forum.edit', 'admins', ''),
('hfnu.admin.index', 'admins', ''),
('hfnu.admin.index', 'moderators', ''),
('hfnu.admin.member', 'admins', ''),
('hfnu.admin.member', 'moderators', ''),
('hfnu.admin.notify.delete', 'admins', ''),
('hfnu.admin.notify.delete', 'moderators', ''),
('hfnu.admin.notify.list', 'admins', ''),
('hfnu.admin.notify.list', 'moderators', ''),
('hfnu.admin.rank.create', 'admins', ''),
('hfnu.admin.rank.create', 'moderators', ''),
('hfnu.admin.rank.delete', 'admins', ''),
('hfnu.admin.rank.delete', 'moderators', ''),
('hfnu.admin.rank.edit', 'admins', ''),
('hfnu.admin.rank.edit', 'moderators', '');
