INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.ban', 'havefnubb~acl2.admin.ban');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.category', 'havefnubb~acl2.admin.category');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.category.create', 'havefnubb~acl2.admin.category.create');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.category.delete', 'havefnubb~acl2.admin.category.delete');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.category.edit', 'havefnubb~acl2.admin.category.edit');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.config', 'havefnubb~acl2.admin.config');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.config.edit', 'havefnubb~acl2.admin.config.edit');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.forum', 'havefnubb~acl2.admin.forum');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.forum.create', 'havefnubb~acl2.admin.forum.create');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.forum.delete', 'havefnubb~acl2.admin.forum.delete');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.forum.edit', 'havefnubb~acl2.admin.forum.edit');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.index', 'havefnubb~acl2.admin.index');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.member', 'havefnubb~acl2.admin.member');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.notify.delete', 'havefnubb~acl2.admin.notify.delete');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.notify.list', 'havefnubb~acl2.admin.notify.list');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.rank.create', 'havefnubb~acl2.admin.rank.create');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.rank.delete', 'havefnubb~acl2.admin.rank.delete');
INSERT INTO %%PREFIX%%jacl2_subject (id_aclsbj, label_key) VALUES ('hfnu.admin.rank.edit', 'havefnubb~acl2.admin.rank.edit');

INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.ban', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.ban', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.category', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.category', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.category.create', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.category.delete', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.category.edit', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.config', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.config', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.config.edit', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.forum', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.forum.create', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.forum.delete', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.forum.edit', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.index', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.index', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.member', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.member', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.notify.delete', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.notify.delete', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.create', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.create', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.delete', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.delete', 'moderators', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.edit', 'admins', '');
INSERT INTO %%PREFIX%%jacl2_rights (id_aclsbj, id_aclgrp, id_aclres) VALUES ('hfnu.admin.rank.edit', 'moderators', '');
