#!/usr/bin/env bash

COMMAND="$1"
shift

if [ "$APPBRANCH" == "" ]; then
  #export APPBRANCH=$(git rev-parse --abbrev-ref HEAD)
  export APPBRANCH=master
fi

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: "
    echo "- Into php: reset, rights, clean-temp, install, composer-install,"
    echo "  composer-update, unit-tests"
    echo "- To enter into the php container: shell, shellroot"
    echo "- to enter into a interactive database shell: mysql"
    exit 1;
fi

case $COMMAND in
    clean-temp)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh clean_tmp;;
    reset)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh reset;;
    install)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh install;;
    rights)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh rights;;
    composer-install)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh composer_install;;
    composer-update)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh composer_update;;
    unit-tests)
        docker exec -t -i hfn_${APPBRANCH}_test_php appctl.sh unit-tests $@;;
    shell)
       docker exec -it --user usertest hfn_${APPBRANCH}_test_php  /bin/bash -l;;
    shell-root)
       docker exec -it hfn_${APPBRANCH}_test_php  /bin/bash  -l;;
    mysql)
      docker exec -it hfn_${APPBRANCH}_test_mysql mysql -u test_user -pjelix testapp
      ;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac

