version: '3.4'
services:
  mysql:
    image: mariadb:10-focal
    container_name: hfn_${APPBRANCH}_test_mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #--default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: jelix
      MYSQL_DATABASE: havefnubb
      MYSQL_USER: havefnubb
      MYSQL_PASSWORD: hfnu
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
  php:
    build:
      context: ./docker-conf/phpfpm
      args:
        fpm_user_id: ${JELIX_USER_ID}
        fpm_group_id: ${JELIX_GROUP_ID}
        php_version: ${PHP_VERSION}
    container_name: hfn_${APPBRANCH}_test_php
    environment:
      TLS_CA_CRT_FILENAME: "tests.hfn-CA.crt"
      APP_WEB_PORT: "${APP_WEB_PORT}"
    volumes:
      - "../:/jelixapp/"
      - "./docker-conf/certs:/customcerts"
    networks:
      - default
    depends_on:
      - mysql
  web:
    image: nginx:alpine
    container_name: hfn_${APPBRANCH}_test_web
    hostname: havefnubb.hfn
    volumes:
      - "./docker-conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"
      - "../:/jelixapp/"
    command: /bin/sh -c "nginx -g 'daemon off;'"
    ports:
      - "${APP_WEB_PORT}:80"
    networks:
      default:
         aliases:
           - havefnubb.hfn
    depends_on:
      - php
volumes:
  mysql_data:
    name: "hfn_${APPBRANCH}_mysql_data"


