<div id="hfnuadmin-help"><img src="{$j_basepath}hfnu/images/add.png" alt="click to view the help" /> Help</div>
<div class="hfnuadmin-help">
    <p>
    This page allow you to configure the behaviors of your forum.
    Here are in details, tab by tab, what is permits to do :
    </p>
    <h4>General</h4>
    <ul>
        <li>This tab permits to configure the globale part of your forum.
        <ul>
            <li>Give a name to your forum</li>
            <li>Provide a slogan to it</li>
            <li>Define rules of use, which if fill, will appear a link of the rules on the forum index page</li>
            <li>Put the email of the webmaster (which will be used by the mailer)</li>
            <li>Put the email of the administrator</li>
            <li>Define the time zone of the entire forum. This value could be changed by each of the member with his profile page</li>
        </ul>
        </li>
    </ul>
    <h4>Messages</h4>
    <ul><li>This tab permits to configure the size and number of messages,thread,replies by page.</li></ul>
    <h4>Importants threads</h4>
    <ul><li>This tab permits to define from the quantity of messages, if the thread is considering as important.</li></ul>
    <h4>Flood Protection</h4>
    <ul><li>This tab permits to manage the quantity of created threads by the same member.</li></ul>
    <h4>Members</h4>
    <ul>
        <li>
        This tabs permits to manage :
        <ul><li>if the guest are autorized to create threads
        (if this is the case a <acronym title="a type of challenge-response test used in computing to ensure that the response is not generated by a computer.">captcha</acronym> will avoid robots to create unsolicited threads also called <acronym title="unsolicited bulk messages indiscriminately">SPAM</acronym>)</li>
            <li>the number of displayed members by page on the <a href="{jurl 'havefnubb~members:index'}">list of members</a></li>
            <li>the autorized size of the avatar of the members</li>
        </ul>
        </li>
    </ul>
    <h4>Socials Network</h4>
    <ul><li>This tab permits to display or not a little button to share a thread on the network of our choice</li></ul>
</div>
