;<?php die('');?>
isWindows=1
enableOldActionSelector=
use_error_handler=1
dbProfils="dbprofils.ini.php"
unusedModules=
trustedModules=
checkTrustedModules=
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/"
timeZone="Europe/Paris"
theme=default
charset="UTF-8"
locale=fr_FR
startAction="default:index"
startModule=havefnubb
[coordplugins]
auth="auth.coord.ini.php"
jacl2="jacl2.coord.ini.php"
history="history.coord.ini.php"
flood="flood.coord.ini.php"
hfnuinstalled="hfnuinstalled.coord.ini.php"
banuser="banuser.coord.ini.php"
timeout="timeout.coord.ini.php"
autolocale="autolocale.coord.ini.php"
[tplplugins]
defaultJformsBuilder=html
[responses]
html=fnuHtmlResponse
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="D:\DOCUMENT_ROOT\www_havefnubb\responses/fnuHtmlResponse.class.php"
redirect.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseBinary.class.php"
text.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXmlrpc.class.php"
xul.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXul.class.php"
xuloverlay.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulPage.class.php"
rdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRdf.class.php"
xml.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXml.class.php"
zip.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseTcpdf.class.php"
soap.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseHtml.class.php"
[_coreResponses]
html=jResponseHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
html.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseHtml.class.php"
redirect.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseBinary.class.php"
text.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXmlrpc.class.php"
xul.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXul.class.php"
xuloverlay.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXulPage.class.php"
rdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRdf.class.php"
xml.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseXml.class.php"
zip.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseTcpdf.class.php"
soap.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core/response/jResponseHtml.class.php"
[error_handling]
messageLogFormat="%date%\t[%code%]\t%msg%\t%file%\t%line%\n"
logFile="error.log"
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
quietMessage="Une erreur technique est survenue. Désolé pour ce désagrément."
showInFirebug=
default="ECHOQUIET EXIT LOGFILE"
error="ECHOQUIET EXIT LOGFILE"
warning="ECHOQUIET LOGFILE"
notice=
strict=
exception="ECHOQUIET LOGFILE"
[compilation]
checkCacheFiletime=
force=
[urlengine]
engine=significant
enableParser=1
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/"
jelixWWWPath="/jelix/"
defaultEntrypoint=index
entrypointExtension=".php"
notfoundAct="havefnubb~error:notfound"
simple_urlengine_https=
significantFile="urls.xml"
urlScript="/index.php"
urlScriptPath="/"
urlScriptName="index.php"
urlScriptId=index
urlScriptIdenc=index
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
hfnuadmin="jacl2db~*@classic, jauth~*@classic, jacl2db_admin~*@classic, jauthdb_admin~*@classic, master_admin~*@classic, hfnuadmin~*@classic, servinfo~default@classic, hfnusearch~admin@classic, hfnucontact~*@classic, downloads~mgr:index@classic, downloads~mgr:manage@classic, downloads~mgr:config@classic, downloads~mgr:dls@classic"
install="hfnuinstall~*@classic"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
rdf=1
hfnuadmin=1
install=1
[logfiles]
default="messages.log"
[mailer]
webmasterEmail="webmaster@domain.com"
webmasterName=webmaster
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
smtpHost=localhost
smtpPort=
smtpSecure=
smtpHelo=
smtpAuth=1
smtpUsername=
smtpPassword=
smtpTimeout=10
[acl]
driver=
[acl2]
driver=db
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/wymeditor/config/default.js"
default.skin.default="jelix/wymeditor/skins/default/screen.css"
[zones]
disableCache=
[classbindings]
[_allBasePath]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/"
1="D:\DOCUMENT_ROOT\www_havefnubb\modules/"
2="D:\DOCUMENT_ROOT\www_havefnubb\plugins/auth/"
3="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/"
4="D:\DOCUMENT_ROOT\www_havefnubb\plugins/db/"
5="D:\DOCUMENT_ROOT\www_havefnubb\plugins/tpl/"
[_modulesPathList]
jelix="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/core-modules/jelix/"
jacl2db="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/jacl2db/"
jacldb="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/jacldb/"
jauth="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/jauth/"
junittests="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/junittests/"
jWSDL="D:\DOCUMENT_ROOT\www_havefnubb\lib/jelix-modules/jWSDL/"
havefnubb="D:\DOCUMENT_ROOT\www_havefnubb\modules/havefnubb/"
hfnuadmin="D:\DOCUMENT_ROOT\www_havefnubb\modules/hfnuadmin/"
hfnucontact="D:\DOCUMENT_ROOT\www_havefnubb\modules/hfnucontact/"
hfnuinstall="D:\DOCUMENT_ROOT\www_havefnubb\modules/hfnuinstall/"
hfnusearch="D:\DOCUMENT_ROOT\www_havefnubb\modules/hfnusearch/"
jcommunity="D:\DOCUMENT_ROOT\www_havefnubb\modules/jcommunity/"
jmessenger="D:\DOCUMENT_ROOT\www_havefnubb\modules/jmessenger/"
jtags="D:\DOCUMENT_ROOT\www_havefnubb\modules/jtags/"
servinfo="D:\DOCUMENT_ROOT\www_havefnubb\modules/servinfo/"
[_pluginsPathList_acl]
db="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/acl/db/"
[_pluginsPathList_acl2]
db="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/acl2/db/"
[_pluginsPathList_auth]
class="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/auth/class/"
db="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/auth/db/"
lds="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/auth/lds/"
[_pluginsPathList_coord]
auth="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/auth/"
autolocale="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/autolocale/"
history="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/history/"
jacl="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/jacl/"
jacl2="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/jacl2/"
magicquotes="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/magicquotes/"
zendframework="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/coord/zendframework/"
banuser="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/banuser/"
flood="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/flood/"
hfnuinstalled="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/hfnuinstalled/"
jGoogleAnalytics="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/jGoogleAnalytics/"
timeout="D:\DOCUMENT_ROOT\www_havefnubb\plugins/coord/timeout/"
[_pluginsPathList_db]
intuition="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/db/intuition/"
mysql="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/db/mysql/"
oci="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/db/oci/"
pgsql="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/db/pgsql/"
sqlite="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/db/sqlite/"
[_pluginsPathList_jforms]
html="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/jforms/html/"
htmllight="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/jforms/htmllight/"
[_tplpluginsPathList_common]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/common/"
1="D:\DOCUMENT_ROOT\www_havefnubb\plugins/tpl/common/"
[_tplpluginsPathList_html]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/html/"
1="D:\DOCUMENT_ROOT\www_havefnubb\plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/text/"
1="D:\DOCUMENT_ROOT\www_havefnubb\plugins/tpl/text/"
[_tplpluginsPathList_xml]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/xml/"
[_tplpluginsPathList_xul]
0="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/tpl/xul/"
[_pluginsPathList_urls]
basic_significant="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/urls/basic_significant/"
significant="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/urls/significant/"
simple="D:\DOCUMENT_ROOT\www_havefnubb\lib\jelix/plugins/urls/simple/"
[_trustedModules]
0=jelix
1=jacl2db
2=jacldb
3=jauth
4=junittests
5=jWSDL
6=havefnubb
7=hfnuadmin
8=hfnucontact
9=hfnuinstall
10=hfnusearch
11=jcommunity
12=jmessenger
13=jtags
14=servinfo
